routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();



Route::middleware(['authjwtcostum'])->group(function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    //User
    // Route::resource('user', App\Http\Controllers\UserController::class);

    //Customer
    Route::resource('customer', App\Http\Controllers\CustomerController::class);
    Route::get('customers/get', [App\Http\Controllers\CustomerController::class, 'getCustomers'])->name('customer.getCustomers');

    //Inventory
    Route::resource('inventory', App\Http\Controllers\InventoryController::class);
    Route::get('inventories/get', [App\Http\Controllers\InventoryController::class, 'getInventories'])->name('inventory.getInventories');
});

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Yajra\DataTables\Facades\Datatables;

class InventoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('inventory.index');
    }

    public function getInventories()
    {   
        $currentUser = session('authMsg');

        $responseInventory = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/inventory');
        
        if($responseInventory['success'])
        {
            $inventory  = array_map(function ($n)
            {
                $n['isDisabled'] = $n['isDisabled'] ? "Inactive" : "Active";
                return $n;
            }, $responseInventory['message']);

            return Datatables::collection($inventory)->make(true);
            
        }
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/inventory/index.blade.php
@extends('adminlte::page')

@section('title', 'Inventory')

@section('content_header')
<h1>Inventory</h1>
@stop

@section('content')
<div class="card">
    <div class="card-header">
        <a href="{{route('customer.create')}}" class="btn btn-primary mr-2">Add New</a>
    </div>
    <div class="card-body">
        <table id="allInventory" class="table table-bordered text-nowrap" style="width:100%">
            <thead class="thead-light">
                <tr>
                    <!--<th>&nbsp;</th>-->
                    <th>Name</th>
                    <th>Category</th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Unit Type</th>
                    <th>Status</th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    $('#allInventory').DataTable( {  
        "fnDrawCallback": function( oSettings ) {                     
                    $('[data-toggle="tooltip"]').tooltip({
                        trigger : 'hover'
                    });   
                },
        select:{
            style:     'os',
            className: 'row-selected'
        },
        responsive: true,
        "language": {
            processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading..n.</span> '
        },
        "scrollX":true,
        "fixedColumns": {
            "leftColumns": 3
        },
        "processing": true,
        "serverSide": true,
        "ajax": {
                    "url": "{{ route('inventory.getInventories') }}",
                    "dataType": "json",
                    "type": "GET",
                    "data":{ _token: "{{csrf_token()}}"},
                    
                },
        "autoWidth" : true,
        "columns": [
            { "data": "name", "name": 'name' },
            { "data": "category", "name": 'category' },
            { "data": "unit_price", "name": 'unit_price' },
            { "data": "quantity", "name": 'quantity' },
            { "data": "unit_type", "name": 'unit_type' },
            { "data": "isDisabled", "name": 'isDisabled' },
        ],

    })
</script>
@stop