routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();



Route::middleware(['authjwtcostum'])->group(function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    //User
    // Route::resource('user', App\Http\Controllers\UserController::class);

    //Customer
    Route::resource('customer', App\Http\Controllers\CustomerController::class);
    Route::get('customers/get', [App\Http\Controllers\CustomerController::class, 'getCustomers'])->name('customer.getCustomers');

    //Inventory
    Route::resource('inventory', App\Http\Controllers\InventoryController::class);
    Route::get('inventories/get', [App\Http\Controllers\InventoryController::class, 'getInventories'])->name('inventory.getInventories');
});

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Yajra\DataTables\Facades\Datatables;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('customer.index');
    }

    public function getCustomers()
    {   
        $currentUser = session('authMsg');

        $responseUser = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/user');
        if($responseUser['success'])
        {
            $user = array_column($responseUser['message'], 'name', 'id');
        }
        
        $responseCustomer = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/customer');
        
        if($responseCustomer['success'])
        {
            $customers  = array_map(function ($n) use ($user)
            {
                return [
                
                    "id" => $n['id'],
                    "name" => "<a href='".route('customer.show', $n['id'])."'>".$n['name']."</a>",
                    "category" => $n['category'],
                    "domicile" => $n['domicile'],
                    "address" => $n['address'],
                    "email" => $n['email'],
                    "phone" => $n['phone'],
                    "lat" => $n['lat'],
                    "lng" => $n['lng'],
                    "status" => $n['isDisabled'] ? "Inactive" : "Active",
                    "credit_limit" => $n['credit_limit'],
                    "pic" => isset($user[$n['pic']]) ? $user[$n['pic']] : $n['pic'],
                    "action" => '<a href='.route('customer.show', $n['id']).' class="btn btn-xs btn-success" data-title="View Detail"><i class="fas fa-info-circle"></i></a> <a href="'.route('customer.edit', $n['id']).'" class="btn btn-xs btn-warning" data-title="Edit"><i class="fas fa-edit"></i></a></td>',
                    "created_at" => $n['created_at'],
                    "updated_at" => $n['updated_at']
                
                ];
            }, $responseCustomer['message']);
            
        }

        return Datatables::collection($customers)->rawColumns(['name', 'action'])->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $role = "Sales,Admin";
        $currentUser = session('authMsg');
        $responseUser = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/user/role/'.$role);
        $responseCategory = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/customer-category');

        return view('customer.create', [
            'pic' => $responseUser['message'],
            'customerCategory' =>  $responseCategory['message']
            ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'category' => 'required',
            'domicile' => 'required',
            // 'address' => 'required',
            'phone' => 'required',
            'email' => 'required',
            'lat' => 'required',
            'lng' => 'required',
            'credit_limit' => 'required',
            'pic' => 'required',
        ]);

        $currentUser = session('authMsg');
        $request['isDisabled'] = isset($request['isDisabled']) ? true : false;

        if(isset($request['isEdit'])){

            $data = $request->except(['_token', 'isEdit']);
            $updatedBy = [
                'updated_by' => $currentUser['id'],
            ];
            $data = array_merge($data, $updatedBy);

            $response = Http::withToken($currentUser['token'])->put(env('API_URL').'/api/v1/customer/'.$data['id'], $data);

            if(!$response['success'])
            {
                return back()->withInput();
            }
            else
            {
                return redirect()->route('customer.index');
            }
            
            
        }
        else{
            $data = $request->except(['_token']);
            $createdUpdatedBy = [
                'created_by' => $currentUser['id'],
                'updated_by' => $currentUser['id'],
            ];
            $data = array_merge($data, $createdUpdatedBy);

            $response = Http::withToken($currentUser['token'])->post(env('API_URL').'/api/v1/customer', $data);
            if(!$response['success'])
            {
                return back()->withInput();
            }
            else
            {
                return redirect()->route('customer.index');
            }
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = "Sales,Admin";
        
        $currentUser = session('authMsg');
        $responseCustomer = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/customer/'.$id);
        $responseUser = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/user/role/'.$role);
        $responseCategory = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/customer-category');
        
        $customerCategory = array_column($responseCategory['message'], 'name', 'id');

        return view('customer.show', [
            'customer' => $responseCustomer['message'],
            'pic' => $responseUser['message'],
            'customerCategory' =>  $customerCategory
            ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = "Sales,Admin";
        
        $currentUser = session('authMsg');
        $responseCustomer = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/customer/'.$id);
        $responseUser = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/user/role/'.$role);
        $responseCategory = Http::withToken($currentUser['token'])->get(env('API_URL').'/api/v1/customer-category');

        return view('customer.edit', [
            'customer' => $responseCustomer['message'],
            'pic' => $responseUser['message'],
            'customerCategory' =>  $responseCategory['message']
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validated = $request->validate([
            'name' => 'required',
            'category' => 'required',
            'domicile' => 'required',
            // 'address' => 'required',
            'phone' => 'required',
            'email' => 'required',
            'lat' => 'required',
            'lng' => 'required',
            'credit_limit' => 'required',
            'pic' => 'required',
            'isDisabled' => 'required',
        ]);
        $currentUser = session('authMsg');
        $createdUpdatedBy = [
            'created_by' => $currentUser['id'],
            'updated_by' => $currentUser['id'],
        ];
        $data = $request->except(['_token']);
        $data = array_merge($data, $createdUpdatedBy);

        $response = Http::withToken($currentUser['token'])->post(env('API_URL').'/api/v1/customer', $data);
        if(!$response['success'])
        {
            return back()->withInput();
        }
        else
        {
            return redirect()->route('customer.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/create.blade.php
@extends('adminlte::page')

@section('title', 'Add Customers')

@section('content_header')
<h1>Add Customers</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        <div class="box box-primary">
            <!-- form start -->
            <form method="POST" action="{{route('customer.store')}}">
            @csrf
                <div class="box-body">
                    <div class="form-group">
                        <label for="nameInput">Nama</label>
                        <input type="input" class="form-control" name="name" id="nameInput" placeholder="Nama">
                    </div>
                    <div class="form-group">
                        <label for="categoryInput">Kategori</label>
                        <select name="category" class="form-control">
                            <option value="" selected disabled hidden>Kategori</option>
                            @foreach ($customerCategory as $cC)
                            <option value="{{$cC['id']}}">{{$cC['name']}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="domisiliInput">Domisili</label>
                        <input type="input" class="form-control" name="domicile" id="domisiliInput" placeholder="Domisili">
                    </div>
                    <div class="form-group">
                        <label for="addressInput">Alamat</label>
                        <input type="input" class="form-control" name="address" id="addressInput" placeholder="Alamat">
                    </div>
                    <div class="form-group">
                        <label for="phoneInput">Phone Number</label>
                        <input type="input" class="form-control" name="phone" id="phoneInput" placeholder="Phone Number">
                    </div>
                    <div class="form-group">
                        <label for="emailInput">Email</label>
                        <input type="email" class="form-control" name="email" id="emailInput" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="latitudeInput">Latitude</label>
                        <input type="input" class="form-control" name="lat" id="latitudeInput" placeholder="Latitude">
                    </div>
                    <div class="form-group">
                        <label for="longitudeInput">Longitude</label>
                        <input type="input" class="form-control" name="lng" id="longitudeInput" placeholder="Longitude">
                    </div>
                    <div class="form-group">
                        <label for="creditLimitInput">Credit Limit</label>
                        <input type="input" class="form-control" name="credit_limit" id="creditLimitInput" placeholder="Credit Limit">
                    </div>
                    <div class="form-group">
                        <label for="categoryInput">PIC</label>
                        <select name="pic" class="form-control">
                            <option value="" selected disabled hidden>PIC</option>
                            @foreach ($pic as $p)
                            <option value="{{ $p['id'] }}">{{ $p['name'] }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="checkbox">
                    <label>
                        <input type="checkbox" name="isDisabled"> Disabled
                    </label>
                    </div>
                </div>
              <!-- /.box-body -->

                <div class="box-footer">
                    
                    <button class="btn btn-default" style="min-width: 70px;">Cancel</button>
                    <button type="submit" class="btn btn-primary" style="min-width: 70px; float:right;">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
@stop

resources/views/customer/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Customers')

@section('content_header')
<h1>Edit Customers</h1>
@stop

@section('content')

<div class="card">
    <div class="card-body">
        <div class="box box-primary">
            <!-- form start -->
            <form method="POST" action="{{route('customer.store')}}">
            @csrf
                <div class="box-body">
                    <input type="hidden" name="isEdit" value="true">
                    <input type="hidden" name="id" value="{{$customer['id']}}">
                    <div class="form-group">
                        <label for="nameInput">Nama</label>
                        <input type="input" class="form-control" name="name" id="nameInput" placeholder="Nama" @if(!empty(old('name'))) value="{{ old('name') }}" @else value="{{ $customer['name'] }}" @endif>
                    </div>
                    <div class="form-group">
                        <label for="categoryInput">Kategori</label>
                        <select name="category" class="form-control">
                            <option value="" selected disabled hidden>Kategori</option>
                            @foreach ($customerCategory as $cC)
                            <option value="{{$cC['id']}}" @if(!empty(old('category')) && old('category') == $cC['id']) selected @elseif($customer['category'] == $cC['id']) selected @endif>{{$cC['name']}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="domisiliInput">Domisili</label>
                        <input type="input" class="form-control" name="domicile" id="domisiliInput" placeholder="Domisili" @if(!empty(old('domicile'))) value="{{ old('domicile') }}" @else value="{{ $customer['domicile'] }}" @endif>
                    </div>
                    <div class="form-group">
                        <label for="addressInput">Alamat</label>
                        <input type="input" class="form-control" name="address" id="addressInput" placeholder="Alamat" @if(!empty(old('address'))) value="{{ old('address') }}" @else value="{{ $customer['address'] }}" @endif>
                    </div>
                    <div class="form-group">
                        <label for="phoneInput">Phone Number</label>
                        <input type="input" class="form-control" name="phone" id="phoneInput" placeholder="Phone Number"  @if(!empty(old('phone'))) value="{{ old('phone') }}" @else value="{{ $customer['phone'] }}" @endif>
                    </div>
                    <div class="form-group">
                        <label for="emailInput">Email</label>
                        <input type="email" class="form-control" name="email" id="emailInput" placeholder="Email" @if(!empty(old('email'))) value="{{ old('email') }}" @else value="{{ $customer['email'] }}" @endif>
                    </div>
                    <div class="form-group">
                        <label for="latitudeInput">Latitude</label>
                        <input type="input" class="form-control" name="lat" id="latitudeInput" placeholder="Latitude" @if(!empty(old('lat'))) value="{{ old('lat') }}" @else value="{{ $customer['lat'] }}" @endif>
                    </div>
                    <div class="form-group">
                        <label for="longitudeInput">Longitude</label>
                        <input type="input" class="form-control" name="lng" id="longitudeInput" placeholder="Longitude" @if(!empty(old('lng'))) value="{{ old('lng') }}" @else value="{{ $customer['lng'] }}" @endif>
                    </div>
                    <div class="form-group">
                        <label for="creditLimitInput">Credit Limit</label>
                        <input type="input" class="form-control" name="credit_limit" id="creditLimitInput" placeholder="Credit Limit" @if(!empty(old('credit_limit'))) value="{{ old('credit_limit') }}" @else value="{{ $customer['credit_limit'] }}" @endif>
                    </div>
                    <div class="form-group">
                        <label for="categoryInput">PIC</label>
                        <select name="pic" class="form-control">
                            <option value="" selected disabled hidden>PIC</option>
                            @foreach ($pic as $p)
                            <option value="{{ $p['id'] }}" @if(!empty(old('pic')) && old('pic') == $p['id']) selected @elseif($customer['pic'] == $p['id']) selected @endif>{{ $p['name'] }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="checkbox">
                    <label>
                        <input type="checkbox" name="isDisabled" @if($customer['isDisabled']) checked @endif> Disabled
                    </label>
                    </div>
                </div>
              <!-- /.box-body -->

                <div class="box-footer">
                    
                    <button class="btn btn-default" style="min-width: 70px;">Cancel</button>
                    <button type="submit" class="btn btn-primary" style="min-width: 70px; float:right;">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
@stop

resources/views/customer/index.blade.php
@extends('adminlte::page')

@section('title', 'Customers')

@section('content_header')
<h1>Customers</h1>
@stop

@section('content')
<div class="card">
    <div class="card-header">
        <a href="{{route('customer.create')}}" class="btn btn-primary mr-2">Add New</a>
    </div>
    <div class="card-body">
        <table id="allCustomer" class="table table-bordered text-nowrap" style="width:100%">
            <thead class="thead-light">
                <tr>
                    <!--<th>&nbsp;</th>-->
                    <th>Name</th>
                    <th>Category</th>
                    <th>Domicile</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Credit Limit</th>
                    <th>PIC</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
<script>
    $('#allCustomer').DataTable( {  
        "fnDrawCallback": function( oSettings ) {                     
                    $('[data-toggle="tooltip"]').tooltip({
                        trigger : 'hover'
                    });   
                },
        select:{
            style:     'os',
            className: 'row-selected'
        },
        responsive: true,
        "language": {
            processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading..n.</span> '
        },
        "scrollX":true,
        "fixedColumns": {
            "leftColumns": 3
        },
        "processing": true,
        "serverSide": true,
        "ajax": {
                    "url": "{{ route('customer.getCustomers') }}",
                    "dataType": "json",
                    "type": "GET",
                    "data":{ _token: "{{csrf_token()}}"},
                    
                },
        "autoWidth" : true,
        "columns": [
            { "data": "name", "name": 'name' },
            { "data": "category", "name": 'category' },
            { "data": "domicile", "name": 'domicile' },
            { "data": "address", "name": 'address' },
            { "data": "phone", "name": 'phone' },
            { "data": "email", "name": 'email' },
            { "data": "credit_limit", "name": 'credit_limit' },
            { "data": "pic", "name": 'pic' },
            { "data": "status", "name": 'status' },
            { "data": "action", "name": 'action' },
        ],

    })
</script>
@stop

resources/views/customer/show.blade.php
@extends('adminlte::page')

@section('title', 'Customer Details')

@section('content_header')
<h1>Customer Details</h1>
@stop

@section('content')
<div class="card">
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-4">Nama:</dt><dd class="col-sm-8">{{ $customer['name'] }}</dd>
            <dt class="col-sm-4">Kategori:</dt><dd class="col-sm-8">{{ $customerCategory[$customer['category']] }}</dd>
            <dt class="col-sm-4">Domisili:</dt><dd class="col-sm-8">{{ $customer['domicile'] }}</dd>
            <dt class="col-sm-4">Alamat:</dt><dd class="col-sm-8">{{ $customer['address'] }}</dd>
            <dt class="col-sm-4">Phone Number:</dt><dd class="col-sm-8">{{ $customer['phone'] }}</dd>
            <dt class="col-sm-4">Email</dt><dd class="col-sm-8">{{ $customer['email'] }}</dd>
            <dt class="col-sm-4">Latitude</dt><dd class="col-sm-8">{{ $customer['lat'] }}</dd>
            <dt class="col-sm-4">Credit Limit</dt><dd class="col-sm-8">{{ $customer['lng'] }}</dd>
            <dt class="col-sm-4">PIC</dt><dd class="col-sm-8">{{ $customer['pic'] }}</dd>
            <dt class="col-sm-4">Status</dt><dd class="col-sm-8">{{ $customer['isDisabled'] ? 'Inactive' : 'Active' }}</dd>
        </dl>
    </div>
</div>
@stop

@section('css')
<link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
@stop